[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 2

[[main]]
  identifier = "posts"
  name = "文章"
  url = "posts"
  weight = 4

[[main]]
  identifier = "fav"
  name = "收藏夹"
  url = "fav"
  weight = 5

[[main]]
  identifier = "showcase"
  name = "Showcase"
  url = "showcase"
  weight = 6